### ISSUE TITLE
AreNuGetPackagesSafe task failed unexpectedly

### ISSUE THREAD

**Issue by jkariotisAtNexIt** [OWASP/SafeNuGet#11]
Error   1   The "AreNuGetPackagesSafe" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'C:\Projects\Alme\Agent\Development\NextIT.Alme.Server\packages\SafeNuGet.1.0.9\build\cache\unsafepackages.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at Owasp.SafeNuGet.Unsafe.PackageListLoader.GetCachedUnsafePackages(String cachePath, Int32 cacheTimeInMinutes, Boolean& cacheHit)
   at Owasp.SafeNuGet.AreNuGetPackagesSafe.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() NextIT.Utilities.Generics

**Comment by git-hub-user** [comment]
I encounter this issue intermittently. In my case, I have 3 start-up projects: 2 web applications and a console application. The error occurs both when starting with debugging (F5) and when (re)building all.

It did some investigation with Process Monitor. These are the results:

### First task
**Process**
Name:	MSBuild.exe
Command Line:	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe /nologo /nodemode:1 /nodeReuse:true
PID:	1220
Parent PID:	10588

**Event**
Event Class:	File System
Operation:	CreateFile
Result:	SUCCESS
Path:	...\WebApp\packages\SafeNuGet.1.0.10\build\cache\unsafepackages.xml.new
Duration:	0.0001743
Desired Access:	Generic Write, Read Attributes
Disposition:	OverwriteIf
Options:	Synchronous IO Non-Alert, Non-Directory File, Open No Recall
Attributes:	n/a
ShareMode:	Read
AllocationSize:	0
OpenResult:	Overwritten

### Second task
**Process**
PID:	12624
Parent PID:	10588

**Event**
Event Class:	File System
Operation:	CreateFile
Result:	SHARING VIOLATION
Path:	...\WebApp\packages\SafeNuGet.1.0.10\build\cache\unsafepackages.xml.new
Duration:	0.0000357
Desired Access:	Generic Write, Read Attributes
Disposition:	OverwriteIf
Options:	Synchronous IO Non-Alert, Non-Directory File, Open No Recall
Attributes:	n/a
ShareMode:	Read
AllocationSize:	0

### Conclusion
The Parent PID belongs to Visual Studio 2017. It is clear that msbuild is started in parallel and both processes attempt to open the same file for writing. It the second file is not granted the access, the build fails.
